<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Protobuf.Grpc.ClientFactory" />
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\UmaDb.Csharp\UmaDb.Csharp.csproj" />
    </ItemGroup>
</Project>