<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <RootNamespace>Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Setup.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FsUnit.xUnit" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Protobuf.Grpc.ClientFactory" />
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\UmaDb.Core\UmaDb.Core.fsproj" />
      <ProjectReference Include="..\UmaDb.Fsharp\UmaDb.Fsharp.fsproj" />
    </ItemGroup>
    <ItemGroup>
      <None Include="certs\ca-key.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Include="certs\ca.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Include="certs\server-key.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Include="certs\server.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <Compile Include="Core\SimpleConnectivity.fs" />
      <Compile Include="Core\SocketExhautions.fs" />
      <Compile Include="Client\Operations.fs" />
      <Compile Include="Client\Connecting.fs" />
      <Compile Include="Client\Reading.fs" />
    </ItemGroup>
</Project>