<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Errors.fs" />
        <Compile Include="Types.fs" />
        <Compile Include="Extensions.fs" />
        <Compile Include="UmaClient.fs" />
        <Compile Include="ConnectionBuilder.fs" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\UmaDb.Core\UmaDb.Core.fsproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="FSharp.Control.TaskSeq" />
      <PackageReference Include="FSharp.Core" />
      <PackageReference Include="IcedTasks" />
    </ItemGroup>
</Project>
