<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Client</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Messages.fs"/>
        <Compile Include="DcbService.fs"/>
        <Compile Include="UmaConnection.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="protobuf-net" />
        <PackageReference Include="protobuf-net.Grpc" />
        <PackageReference Include="Protobuf.Grpc.ClientFactory" />
        <PackageReference Include="System.Security.Cryptography.Pkcs" />
        <PackageReference Include="System.ServiceModel.Primitives" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="FSharp.Control.TaskSeq"/>
    </ItemGroup>
</Project>
