<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Client</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Messages.fs"/>
        <Compile Include="DcbService.fs"/>
        <Compile Include="UmaConnection.fs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="protobuf-net.Grpc" />
        <PackageReference Include="System.Security.Cryptography.Pkcs" />
    </ItemGroup>
</Project>
